#!/bin/sh

# Set commons variables names
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
GUIX_EXTRA=$HOME/.guix-extra

# For each project
for PROJECT_NAME in k8x1d-emacs k8x1d-emacs-pgtk
do
    # Create channel
    guix pull --profile="$GUIX_EXTRA/$PROJECT_NAME/guix"

    # Install packages
    "$GUIX_EXTRA/$PROJECT_NAME/guix/bin/guix" package --manifest=$PROJECT_NAME.scm --profile="$GUIX_EXTRA_PROFILES/$PROJECT_NAME/$PROJECT_NAME"

done