(deftheme k8x1d-light
  "Created 2023-09-07.")

(custom-theme-set-faces
 'k8x1d-light
 '(default ((t (:family "Iosevka Term" :foundry "UKWN" :width normal :height 120 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#0C0D0D" :background "#FFFEFD" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#0C0D0D"))))
 '(fixed-pitch ((t (:family "Iosevka Term" :foundry "UKWN" :width normal :height 1.0 :weight light :slant normal))))
 '(variable-pitch ((t (:family "Iosevka Aile" :foundry "UKWN" :width normal :height 1.0 :weight light :slant normal))))
 '(escape-glyph ((t (:foreground "#278C87"))))
 '(homoglyph ((t (:foreground "#0044CC"))))
 '(minibuffer-prompt ((t (:foreground "#5D00DA" :background "#FFFEFD"))))
 '(highlight ((t (:background "#F5F2F0"))))
 '(region ((t (:extend t :background "#D1CFCF"))))
 '(shadow ((t (:foreground "#EBE9E7"))))
 '(secondary-selection ((t (:extend t :background "#EBE9E7"))))
 '(trailing-whitespace ((t (:background "#D1CFCF"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:weight light :foreground "#0C0D0D"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :foreground "#706F6F"))))
 '(font-lock-constant-face ((t (:weight light :foreground "#0C0D0D"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#000000"))))
 '(font-lock-keyword-face ((t (:weight light :slant italic :foreground "#0C0D0D"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:weight medium :foreground "#0C0D0D"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#0C0D0D" :background "#E3E1E0"))))
 '(font-lock-type-face ((t (:weight light :foreground "#0C0D0D"))))
 '(font-lock-variable-name-face ((t (:weight light :foreground "#000000"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#B30000"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line :position nil) :foreground "#000000" :background "#F8F6F4"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:weight light :background "#FFFEFD"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line :position nil) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line :position nil) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line :position nil) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:foreground "#F5F2F0" :background "#D1CFCF"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#F5F2F0" :style nil) :foreground "#0C0D0D" :background "#E3E1E0"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#F5F2F0" :style nil) :foreground "#706F6F" :background "#F8F6F4"))))
 '(isearch ((t (:weight bold :foreground "#F5F2F0" :background "#0044CC"))))
 '(isearch-fail ((t (:background "#B30000"))))
 '(lazy-highlight ((t (:foreground "#0C0D0D" :background "#e0a500"))))
 '(match ((t (:foreground "#F8F6F4" :background "#0044CC"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:background "#e0a500")))))

(provide-theme 'k8x1d-light)
